### ISSUE TITLE
浏览器访问为空白页面

### ISSUE THREAD

**Issue by 1fvyuio333** [Marven11/EtherGhost#2]
windows 11运行后，浏览器访问页面为空白。
![image](https://github.com/user-attachments/assets/1121d90c-757c-42a3-814b-7c9233a5459f)

**Comment by Marven11** [comment]
看一下网络请求记录和黑框终端打印的东西，顺便报一下浏览器版本，我本地测试看到的MIME是application/javascript, 应该是没有问题的

**Comment by 1fvyuio333** [comment]
![image](https://github.com/user-attachments/assets/4894f591-f68e-4878-b233-b2edf797abe3)
![image](https://github.com/user-attachments/assets/05cacb5b-71de-44b6-b362-56e1f2ece48f)

版本 129.0.6668.90（正式版本） （64 位）

**Comment by Marven11** [comment]
好的好的，我上完课回来看看，应该不难修复

**Comment by Marven11** [comment]
[ether_ghost_v0.1.0_dev.exe.zip](https://github.com/user-attachments/files/17303482/ether_ghost_v0.1.0_dev.exe.zip)

试试这个版本，应该是pyinstaller的问题，它去调用了系统的旧版python而不是内置的python. 我调整了内置的mimetypes模块，应该可以正确传输mimel了

**Comment by 1fvyuio333** [comment]
成功解决

**Comment by Marven11** [comment]
OKOK
