### ISSUE TITLE
建议用golang+vue编写

### ISSUE THREAD

**Issue by alaywn** [Marven11/EtherGhost#8]
现在很多工具，都选择了golang，因为可以交叉编译，不用操作系统的用户都可以使用，这样受众群体大很多

**Comment by Marven11** [comment]
给你键盘你来😅（不是

python和golang我都用过，这个项目选择python的原因主要是因为

- python做个人开发比golang方便得多，python语法简洁，不会像golang一样充满simple and stupid的if err != nil
- python跨平台能力要比golang强，python是脚本语言，根本不需要什么“交叉编译”就能在其他操作系统和CPU架构上跑起来
- 我们真的需要裸机运行这个软件？什么人会想在bare metal上运行这个工具？如果不需要的话那“不用操作系统”没有意义
- golang的高性能对这个项目来说根本没有意义，一个webshell管理器要高并发干什么？难道还要ddos目标不成

希望大家在选择编程语言的时候还是要具体问题具体分析，别被某些噱头冲昏了头脑；也不要随大流，看到别人用什么自己就用什么

**Comment by Marven11** [comment]
而且要换也应该是把vue换成svelte，闲得无聊换python干什么

**Comment by alaywn** [comment]
你开心就好
